name: Test Python Package Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Manual test button

permissions:
  contents: read

jobs:
  run-build:
    uses: ./.github/workflows/build.yml
